networks:
  vulnforge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.90.0.0/16
          ip_range: 172.90.240.0/20

services:
  db:
    image: mariadb:10.11-ubi
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb_password
      - MYSQL_DATABASE=pterodactyl
      - MYSQL_USER=pterodactyl
      - MYSQL_PASSWORD=pterodactyl
    networks:
      - vulnforge
    expose:
      - "3306:3306"
      - "33060:33060"

  
  pterodactyl:
    build:
      context: .
      dockerfile: Dockerfile
#      args:
#    environment:
    container_name: cve-2025-49132-pterodactyl
    depends_on:
      - db
    networks:
     - vulnforge
    ports:
      - 80:80
    restart: always
    command: /usr/local/bin/entrypoint.sh
