networks:
  postgres_cve_2025_1094:
    driver: bridge
    ipam:
      config:
      - subnet: 172.90.0.0/16
        ip_range: 172.90.240.0/20

services:
  postgres:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: postgres_cve_2025_1094
    ports:
      - "5432:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    restart: unless-stopped
    networks:
      - postgres_cve_2025_1094
    # healthcheck:
    #   test: ["CMD", "nc", "-z", "localhost", "5432"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3