services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: Europe/Moscow
    container_name: tomcat_cve_2024-50379
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Moscow
    command: ["/opt/tomcat/bin/catalina.sh", "run"]
    restart: always