version: "3.8"

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: Europe/Moscow
    container_name: apache_cve_2021_41773
    ports:
      - "8080:80"
    environment:
      - TZ=Europe/Moscow
    working_dir: /root
    command: ["/usr/local/apache2/bin/apachectl", "-D", "FOREGROUND"]
    restart: always