networks:
  wp_cve-2025-2005-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.90.0.0/16
          ip_range: 172.90.240.0/20

services:
  db:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - wp_cve-2025-2005-net
    expose:
      - "3306:3306"
      - "33060:33060"

  
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORDPRESS_DB_HOST: "db"
        WORDPRESS_DB_USER: "wordpress"
        WORDPRESS_DB_PASSWORD: "wordpress"
        WORDPRESS_DB_NAME: "wordpress"
    environment:
      - WORDPRESS_SITE_TITLE=My VulnForge WP
      - WORDPRESS_ADMIN_EMAIL=admin@vulnforge.com
      - WORDPRESS_ADMIN_USER=vulnforge
      - WORDPRESS_ADMIN_PASSWORD=vulnforge123
      - WP_CLI_ALLOW_ROOT=1
    container_name: wp_cve-2025-2005
    depends_on:
      - db
    networks:
     - wp_cve-2025-2005-net
    ports:
      - 8080:80
    restart: always
    command: /usr/local/bin/init.sh

