networks:
  vulnforge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.90.0.0/16
          ip_range: 172.90.240.0/20

services:
  db:
    image: mariadb:10.4.34
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somevunlforum
      - MYSQL_DATABASE=vulnforum
      - MYSQL_USER=vbulletin
      - MYSQL_PASSWORD=vbulletin
    networks:
      - vulnforge
    expose:
      - "3306:3306"
      - "33060:33060"

  
  vb6:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VB6_DB_HOST: "db"
        VB6_DB_NAME: "vulnforum"
        VB6_DB_USER: "vbulletin"
        VB6_DB_PASSWORD: "vbulletin"
    container_name: cve-2025-48827-vb
    depends_on:
      - db
    networks:
     - vulnforge
    ports:
      - 8080:80
    restart: always
    command: /usr/local/bin/init.sh
