networks:
  flowise_cve_2025_26319:
    driver: bridge
    ipam:
      config: 
      - subnet: 172.90.0.0/16
        ip_range: 172.90.240.0/20

services:
  flowise:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: Europe/Moscow
    container_name: flowise_cve_2025_26319
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Moscow
    command: ["sh", "-c", "/usr/local/bin/entrypoint.sh"]
    restart: unless-stopped
    networks:
      - flowise_cve_2025_26319