networks:
  vulnforge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.90.0.0/16
          ip_range: 172.90.240.0/20

services:
  sudo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cve-2025-32463-sudo
    networks:
      - vulnforge
    ports:
      - 2222:22
    restart: always
    command: /usr/local/bin/entrypoint.sh