# Setup jenkins controller

networks:
  jenkins-cve-2024-43044:
    driver: bridge
    ipam:
      config:
        - subnet: 172.90.0.0/16
          ip_range: 172.90.240.0/20

services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile_controller
    container_name: jenkins_controller
    restart: unless-stopped
    privileged: true
    user: root
    environment:
      - JENKINS_HOME=/var/jenkins_home
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jcas/jenkins.yaml
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      - JENKINS_EXT_URL=http://jenkins:8080
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_controller_data:/var/jenkins_home
      - ./jenkins/jenkins.yaml:/var/jenkins_home/jcas/jenkins.yaml
      - ./groovy/:/var/jenkins_home/groovy
      - ./xml/:/var/jenkins_home/xml
      - ./jar:/var/jenkins_home/jar
      - ./ssh/jenkins_key:/var/lib/jenkins/.ssh/id_rsa:ro
    networks:
      jenkins-cve-2024-43044:

# Setup jenkins agent
  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile_agent
    container_name: jenkins_agent
    privileged: true
    restart: unless-stopped
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=vulnforge_agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    depends_on:
    - jenkins
    volumes:
    - jenkins_agent_data:/home/jenkins:rw
    ports:
      - 2222:22
    networks:
      jenkins-cve-2024-43044:


volumes:
  jenkins_controller_data:
  jenkins_agent_data:


