name: Update CVE List (Text & JSON)

on:
  push:
    branches:
      - main

jobs:
  update-cve-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate CVE list (text and JSON)
        run: |
          CVES=$(find . -type d -iname "CVE*" -printf '%f\n' | sort -t '-' -k2,2n -k3,3n)
          echo "$CVES" > cve_list.txt
          printf '[\n%s\n]\n' "$(echo "$CVES" | sed 's/.*/  "&"/' | paste -sd "," -)" > cve_list.json

      - name: Commit and push changes if needed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add cve_list.txt cve_list.json
            git commit -m "Upd: Update CVE lists (text & JSON)"
            git push
          else
            echo "No changes to commit"
          fi
